# Generated by Django 3.1.1 on 2020-10-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='ordered',
        ),
        migrations.AddField(
            model_name='cart',
            name='in_cart',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='in_cart',
            field=models.BooleanField(default=True),
        ),
    ]
