# Generated by Django 3.1.1 on 2020-10-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20201008_2237'),
        ('orders', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_carts', to='cart.cart'),
        ),
    ]
