# Generated by Django 3.1.1 on 2020-10-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20201009_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_cart',
        ),
    ]
