# Generated by Django 3.1.1 on 2020-10-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_order_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
