# Generated by Django 3.1.1 on 2020-10-10 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_orderinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderInfo',
        ),
    ]
