# Generated by Django 3.1.1 on 2020-10-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_braintree_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='total',
        ),
    ]
